#+TITLE: MimerDesk press release

September 12th, 2003 -
[[http://sachachua.com/blog/p/1103][http://sachachua.com/blog/p/1103]]

#+BEGIN_QUOTE
  Espoo, Finland --- September 11, 2003 --- The new stable release of
  MimerDesk
   introduces Type sets for the freedom of choice in pedagogical
  methodologies,
   a better structured and more intuitive user interface and new tools
  to
   further enhance effective collaboration.

  MimerDesk takes one step closer towards pedagogical independence in
  the sense
   that it is not limited to specific learning process methodologies,
  but instead
   provides the possibility for the user to create Type sets for
  different types
   of learning processes like Problem Based Learning.

  The Project Manager in MimerDesk 2.0 is specifically designed to
  provide more
   efficient manner of carrying out projects asynchronously. This tool
  is ideal
   for group assignments and projects because of its illustrative
  nature.
   The Project Manager includes a dynamic tree structure with unlimited
  levels of
   tasks, participant specific task lists, task dependencies, milestones
  and
   enhanced GANTT charts.

  MimerDesk 2.0 also delivers an enhancement to the Calendar in the form
  of a
   new tool, the Meeting Planner. The main objective of this tool is to
  ease the
   process of arranging meetings with three or more people, be it for a
  school
   project or a board meeting. The Meeting Planner is integrated with
  the
   Calendar so that all meetings that are agreed upon are directly sent
  to the
   participants' Calendars.

  MimerDesk 2.0 introduces a more intuitive and easy-to-use structure in
   the form of top-level tabs that separate Personal, Groups and
  Administration
   tools to form their own wholes. An individual user and group
  administrators
   can dynamically select the desired set of tools to work with and this
  freedom
   makes the environment more flexible and suitable for different types
  of
   communities, groups and individuals.

  As is to be expected, the MimerDesk 2.0 release fixes numerous bugs
  and
   inconsistencies found in previous versions.

  MimerDesk is a Free/Open Source web-based collaborative learning and
  groupwork
   environment software. MimerDesk is published under the GNU GPL
  license

  ([[http://www.gnu.org/copyleft/gpl.html][http://www.gnu.org/copyleft/gpl.html]]).
  The license protects the user's rights
   to use, change and distribute the MimerDesk software. The MimerDesk
  software
   can be downloaded from the project website
  ([[http://www.mimerdesk.org][http://www.mimerdesk.org]]).

  Ionstream Oy is the main developer of the MimerDesk environment and
  has a
   long history of expertise in Internet communities, teaching and
  web-based
   collaborative learning. Ionstream Oy is focused on designing,
  implementing
   and delivering customer-specific collaborative learning and groupware
   solutions.
#+END_QUOTE

Argh. ;)
