#+TITLE: The class is practically running itself

December 18th, 2003 -
[[http://sachachua.com/blog/p/1525][http://sachachua.com/blog/p/1525]]

It's amazing. The class is practically running itself. The time I put
 into making those exercises was definitely worth it. They're off
 solving them or making up their own exercises. With documentation,
 time to explore the system, and the freedom to make mistakes and ask
 questions, the trainees learn almost entirely on their own.

When they do have questions, they tend to ask each other first before
 asking me. I handle the questions they can't figure out from the text
 and clarify things that are fuzzy.

It's really amazing. I hope they'll leave the training confident that
 they can learn whatever else they need to -- considering they learned
 Perl nearly on their own! Because I'm more into getting lots of people
 do Perl, I'm not worried about long-term profitability. After all,
 what training center would do well if they kept encouraging students
 to learn independently?

That said, it was a lot of work preparing the exercises, and I can't
 count the number of times quick thinking and familiarity with UNIX
 made things easier. For example,

#+BEGIN_EXAMPLE
    wget -r -nc --no-parent --proxy-user=secret --proxy-pass=secret http://www.perldoc.com/perl5.6/pod/perl.html
#+END_EXAMPLE

and judicious use of ncftp's mput command (skipping the
 already-uploaded files) allowed me to easily make Perl's documentation
 available even though the server didn't have anything but perl(1).
 Better than manpages, actually, as these were hyperlinked! =)

#+BEGIN_EXAMPLE
    tar zcvf day2.tar.gz /usr/local/training/home/
#+END_EXAMPLE

will allow me to pack up all their work so that I can use my Emacs
 keyboard macro to send it to their listed e-mail addresses. (I should
 get around to making that a defun...)
