#+TITLE: My mom's started blogging!

December 6th, 2004 -
[[http://sachachua.com/blog/p/2471][http://sachachua.com/blog/p/2471]]

(Won't give anyone the URL until she gives the go-ahead.)

I'm reading my mom's very first blog post. I wish she had started
 earlier. These are stories I would never have heard even if I had been
 there. How is it that a journal entry or a letter can feel more
 intimate than spoken conversation or actual presence?

Was I even actually present? When I was in the Philippines, I spent
 most of the time in the Internet room, doing my mail, hacking on
 planner.el or browsing the Net. This was, for me, being in touch with
 the world. At some point in the evening either my dad or my mom would
 call up and say “Come here and talk to us,” and I would try to think
 of whatever they might find interesting in my rather uneventful day.
 Sometimes I'd have lots of stories---after an exam, for example---but
 after the first flush of excitement, we'd peter off. Some days, the
 only time I saw my parents was right before going to sleep. (Don't
 worry, it got better after a while.)

I want to be present. I want to go beyond the anecdotes that just
 graze the surface of one's day. I want to delve beyond the first or
 second thought that comes to mind, to hear the stories from long ago
 or the stories hidden in today's events. I want to think about “why”,
 too, but at a leisurely pace that allows us to really reflect instead
 of scrambling to answer right away.

I think that's it. It's not about being there in real life or not, but
 it's about presence and insight. Going beyond the obvious stuff. It's
 like the way that people who chat with me in real-time might find out
 current events, but people who read this can get an idea of how I
 think. I am somewhat embarrassed to admit that even among my friends I
 think of myself as present in varying degrees.

Anyway. Presence.

Today's stories made me feel present.

My mom's stories today are stories that can only be told on drowsy
 afternoons with nothing else to do---and there's always something more
 to do. These are stories of leisure to be told among long silences,
 and we were never quite a family for long silences. These are stories
 meant to be told and heard at leisure; perfect for letters.

Today's letter was about a family party on my father's side. I would
 have probably not wanted to go to it, would've sat quietly and tried
 to figure out what to talk about if I had gone. I usually dread family
 reunions because there are all these people I'm supposed to know and
 yet don't really, and yet it's difficult to overcome my embarrassment
 at not knowing anyone and actually go and try to get to know people.
 (That probably didn't make sense to you.)

Reading her account of it, though, I felt more \_there\_ than I had
 been, say, during my grandmother's funeral. My mom tells people's
 little stories. She makes them come alive. Next time I go to these
 things, I'll be able to fake knowing a little bit about what's going
 on. I'm almost looking forward to that.

So, dear Mom: Continue writing. Protect that time. Block it off.
 Consider it sacred. Give yourself at least 15 minutes a day to reflect
 on what you did, what you could improve, and where you're going---or
 simply to tell us about some wonderful thing that happened that day.
 Writing on the Internet is this strange mix of writing to loved ones
 as well as complete strangers, and sometimes you'll find you can say
 things to one that you wouldn't have thought of saying to the other.

(Like this reflection on presence, which might not have been a
 conversation I would've started with you but which, now that it's out
 there, I wouldn't mind your comments on. =) )

(Hope other people aren't getting weirded out about these reflective
 blog posts. Think of it like lifehacking. I'm debugging my internal
 processes. Think of this as me thinking out loud, testing my ideas for
 coherence and sensibility. If you really find it strange, e-mail me at
 [[mailto:sacha@free.net.ph][sacha@free.net.ph]] what you like and don't
like hearing about and I'll
 see if I can split off a separate feed for you. See
[[http://sachachua.com/notebook/wiki/WelcomePage][WelcomePage]] for a
 list of my RSS feeds.)

E-Mail from Harvey Chua
