#+TITLE: Today

October 2nd, 2004 -
[[http://sachachua.com/blog/p/2250][http://sachachua.com/blog/p/2250]]

We reviewed all the grammatical structures taken up over the last 25
 chapters. I found grammar easy to remember. I think it's because I
 remember patterns well. That's probably why I can pull almost-random
 information out of my head. On the other hand, I have a hard time
 remembering details, so I'll need to revise a lot for my kanji test on
 Monday afternoon.

After lunch, I got several bug closes back from happy Planner users.
 I just love it when that happens. =)

I also e-mailed someone with Japanese page about emacs-wiki. I told
 him about the change of maintainers and the new way of getting
 versions. =) It was a good opportunity to practice translation, and
 I'm slowly getting the hang of it. I love practicing with
 documentation of my own software... ;)

I met some people from [[http://www.msinet.co.jp][my host company]]
 this afternoon. Apparently, there aren't a lot of Linux projects these
 days, so they're changing our training program. I'll be learning
 Delphi instead. That should make Ranulf quite happy. I'm looking
 forward to learning Delphi. =) (It's a heck of a lot better than
 working with VB, and there's always Kylix for us Linux geeks...)

Managed to survive using Japanese. Understood most of what they said.
 Way, way, cool.

Practiced poi. Took video of what I think might be a fountain. Video
 will be uploaded to
[[http://www.adphoto.com.ph/sacha/][http://www.adphoto.com.ph/sacha/]]
eventually.
 (Probably today.)

Tonight is planner packaging night. After that, I'm going to upload my
 poi videos and relax before tomorrow's cramming session.
