#+TITLE: Page rank and thoughts on online popularity

November 22nd, 2004 -
[[http://sachachua.com/blog/p/2421][http://sachachua.com/blog/p/2421]]

Warning: this entry not expected to be coherent. Following one of my
 software mantras, I will get this entry out the door first, \_then\_
 worry about making my ideas neat. I normally try to be more coherent,
 but today I also need to pack, so I don't have the time to make this
 shorter.

(It's true. Short, clear entries take longer to write.)

I just got mail from dlpusa.com, a Philippine e-commerce site. They
 offered a link exchange, citing their PageRank of 6 and Alexa
 traffic rank of 196,446.

I'm linking to them as a matter of course in this blog entry, but I
 don't think I'll take them up on the link exchange offer. I don't want
 to inflict advertising on my planner pages. Except for Google text
 ads, maybe. =)

Anyway, that made me curious, so I checked my Google PageRank
 through the handy non-toolbar-dependent calculator at

[[http://www.top25web.com/pagerank.php][http://www.top25web.com/pagerank.php]]
. It turns out that
 [[http://sacha.free.net.ph][http://sacha.free.net.ph]] has a pagerank
of 5/10 .

I don't know if PageRank is all that useful for me. People
 generally stumble upon my site looking for very specific things, like
 planner.el or my history notes. (Odd, that.) Or they're my
 friends/family and read my blog in order to find out what's going on
 in my life. (Whoops.) Or they're looking for their own name, and I
 have a higher pagerank than they do.

Most of my URL posts are now over at
[[http://del.icio.us/sachac][http://del.icio.us/sachac]] .
 del.icio.us is cool. You should try it out. I post links here when
 I feel the need for commentary, but del.icio.us is good for
 fire-and-forget as well as social bookmarking.

Actually, what I need is something that'll put a mention in both
 del.icio.us and the URL... Hmm. That'd make a nice remember module.

Anyway, my ego can take the idea that I'm probably just an entry in
 people's RSS aggregators. ;) You know, the kind of thing you subscribe
 to one day, and then are too lazy to remove. Hehehe. I'll try not to
 overload your inbox, then, and I'll try to use meaningful subjects.

Hmm. What is this blog for?

- Not online popularity in itself. That's silly.

- Personal memory. Seriously. It's not your fault that M-x remember is

#+BEGIN_QUOTE
  bound to a convenient shortcut (F9 r SPC on this machine), but
   that's the reason you suffer through all the strangest emacs-lisp
   snippets and commentary on mail that's not actually viewable on the
   Net anyway.
#+END_QUOTE

- Projects I feel deserve more attention. Please check them out. Also,

#+BEGIN_QUOTE
  please tell me about similar stuff I can learn about and link to.
#+END_QUOTE

- The occasional rambling pseudo-essay, like this one. I hope to achieve

#+BEGIN_QUOTE
  [[http://www.paulgraham.org][http://www.paulgraham.org]] -like
  coherence at some point in time.
   I hope said point is before my death.
#+END_QUOTE

- Emacs Lisp code. Shell scripts. Random hacks. Geeky stuff.

- Occasionally, my personal life. Sorry if that freaks you out. =)

If you tell me what you like, I'll write more about it.

So going back to the very first thing... What sites would I like to link
to?

- Thought-provoking questions. Preferably stuff that'll provide me

#+BEGIN_QUOTE
  with procrastination fodder, causing me to go off on a wild tangent
   as I figure out what I think about the issue (and thus avoid having
   to think about the packing I have to do later)...
#+END_QUOTE

- Nifty hacks.

- Insightful blogs. Interesting ideas. Blogs that show an awareness of

#+BEGIN_QUOTE
  a universe outside the author's close circle of friends. That sort
   of thing.
#+END_QUOTE

- Stuff that looks like it should be in my blog, but isn't.

- Yours. I'm curious about the intersection of interests.

Ish.

Drop me a note?

E-Mail%20from%20Marc%20Hil%20Macalua
