#+TITLE: Blogging is alive and well under Emacs

January 2nd, 2004 -
[[http://sachachua.com/blog/p/1570][http://sachachua.com/blog/p/1570]]

in reaction to
[[http://www.sfu.ca/~gswamina/BlogsAreDead.html][http://www.sfu.ca/~gswamina/BlogsAreDead.html]]

I've had a blog for roughly a year and a half now, and I think I'm
 pretty much settling into the routine. Reading
[[http://www.sfu.ca/~gswamina/BlogsAreDead.html][Ganesh's BlogsAreDead]]
post, I think about how I use Emacs to keep track of my notes.

#+BEGIN_QUOTE
  Linearity -- Blogs are linear, ie usually in chronological
   order. My knowledge/experience is non-linear (fortunately). There is
   an obvious mismatch here. I don't see how I can write coherently
  about
   recursive functions, pipelines, privacy and chicks in the same
   post.
#+END_QUOTE

I split this up into several remember-to-planner-plan-page-dwim posts,
 usually cross-linking them with a topic page.

#+BEGIN_QUOTE
  Lack of time -- Everybody seems to be bringing this up. I
   don't post very often, but when I do, they are long ones. If you've
   noticed, my titles are usually one or two words -- “Skills”, “04-1
   Registered”, “Talks”, “Its Tuesday”, $(rand dict). Not very
   descriptive. Often, I remember writing about something, but not able
   to track it down. Sad, really.
#+END_QUOTE

My titles aren't all that descriptive either, but that's what M-x
 planner-search-notes in planner-experimental.el is for. And yes, I
 really hate it if I know I blogged about something but I can't
 remember how to bring it up.

#+BEGIN_QUOTE
  Non-conformance to standards -- When you put together an entry, do
   you check if it confirms to W3C standards every time ? Honestly,
   that's insane. A standard transformation mapping will make life so
   much easier. I now face a problem, how do I convert my old entries ?
   I seem to have used three to four different ways to post my code,
   all of them every inelegant, except for the last.
#+END_QUOTE

I work with plain text.

#+BEGIN_QUOTE
  Immature -- Blogging software is not powerful enough. What
   if I want to quote an email message, or a news thread ? Or simple
   syntax highlighting ? Or even on the fly spell checking (known as
   flyspell-mode in emacs, BTW). Couple this with my non-descriptive
   titles, how do I cross reference things ?
#+END_QUOTE

Emacs is wonderful!

#+BEGIN_QUOTE
  Not cool -- Blogs aren't cool anymore, since every kid
   happens to have his own. When you come across somebody's blog which
   appears to be very interesting, do you take the time to read through
   his archives ? Ofcourse not. More bit bricks.
#+END_QUOTE

I often read through other people's archives. I hope that the
 cross-references with plan pages make it easier for people to see
 related stuff, but I plan to have some kind of search someday.

#+BEGIN_QUOTE
  Stagnant -- “The only thing that is constant is change.”
   Spring->Summer->Fall, so many things change around you. About 28.5%
   (eh !) of your content is stale. Your views on life constantly change
   (you may deny it). Going back and changing stuff just doesn't make
   sense when your entries are chronological.
#+END_QUOTE

I frequently go back and post updates. I also tend to reorganize the
 plan pages fairly often, although that does mean semi-broken day
 links. (Must get those GUIDs up and running!)

Emacs is way cool.
