#+TITLE: One week left

February 18th, 2005 -
[[http://sachachua.com/blog/p/2627][http://sachachua.com/blog/p/2627]]

Seven more days and I'll be home! I need to think about how I'm going
 to spend my summer.

I've realized that I don't \_have\_ to do a lot of advocacy talks.
 People are perfectly capable of taking care of themselves. However, I
 do need to do braindumps of the stuff I learned in Japan, if only so
 that I can summarize them into presentations.

I also don't need to worry about computer science education just yet,
 as I won't be able to do much about it at this point in time. Not with
 just six months before I start grad school...

SO.

What am I going to do?

Adphoto IT geeking

First, there's my family's company. Among other things, I want to work
 on:

- the Adphoto website
 - setting up a good long-distance transfer method for large files: need
to write instructions for FTP.
 - figuring out how my parents can do stock photography online
 - the shoot scheduler

I will set aside regular time for this and my Planner work. =) I think
 it will be tons of fun, and quite an experience. The major thinko I
 just had is that hey, look, I've got practically 24/7 access to a
 bunch of users with different needs. I should take advantage of that.
 Besides, if we get the processes into place, things will be much
 smoother.

Hanging out with friends

One of the strange things about my trip to Japan is how much time I've
 actually spent outside my dorm room. This is in stark contrast to some
 days at home when it was just Internet room -- lunch -- Internet room -
 dinner -- Internet room -- sleep. I think that knowing you'll only be
 someplace for six months really wakes you up. I wanted to meet people
 and see the sights instead of just staying in my dorm room all the
 time.

So you can expect me to be a lot more social when I get back. I want
 to see my parents and my sister---and not just a brief glimpse before
 going to bed. I want to chat with my friends. I want to challenge
 their minds with all these cute little puzzles I'm bringing back home,
 or simply find out what they're interested in. Sure, we all have
 blogs, but it's fun to just relax. =)

This can get expensive, but we'll find ways of keeping the costs down
 so that it's sustainable. We'll stay at houses and parks instead of in
 malls, for one.

There are so many people I want to talk to, so many people I'd like to
 just relax and chat with. =)

‘course I might still go all introverted on occasion, but I think I've
 tipped over into extrovert mode. =)

Reading up on personal information management

In preparation for grad school, of course.

Street performing

I have a staff, a pair of electric poi, and two diabolo sets. I'm
 looking forward to doing pair diabolo with Kathy. That's not enough
 for a full circus-in-a-suitcase kind of gig, but it's a good start.

Taking lots of strange classes

Cooking, for one.
