#+TITLE: Geekwear

September 16th, 2005 -
[[http://sachachua.com/blog/p/2981][http://sachachua.com/blog/p/2981]]

I actually like wearing geek swag: clothes and accessories with a
 logo or geek reference. Geek swag identifies me to other geeks and
 makes it easier for geeks of similar interests to start conversations
 with me. [[http://sachachua.com/notebook/wiki/2005.07.06#2][I'm not the
only one who thinks so.]]

I want geek swag, but I want geek swag that fits my lifestyle.

- I occasionally wear T-shirts. My Linux conference baby tee is

#+BEGIN_QUOTE
  much-loved and often-worn.
#+END_QUOTE

- I really want some kind of geek bag, but I also want my

#+BEGIN_QUOTE
  multi-compartment tote with all sorts of nifty pockets.
#+END_QUOTE

- I want a geek sweater or hoodie that I can wear more often than a
T-shirt.

- I want geek earrings. (Anyone who makes pretty Tux earrings for a

#+BEGIN_QUOTE
  reasonable price will have my business.)
#+END_QUOTE

- I want an index card holder with a pen loop. This is more for my

#+BEGIN_QUOTE
  D*I*Y Planner geekiness.
#+END_QUOTE

- I want stickers. My current sticker reads “The geek shall inherit

#+BEGIN_QUOTE
  the earth.” It's bright red and white, and can't help but draw
   attention to my ubercute-and-small laptop.
#+END_QUOTE

- I want a D*I*Y 1″ or 1.5″ zippered binder, just because. Yes, I have

#+BEGIN_QUOTE
  far too many binders already. That doesn't stop me from wanting a
   D*I*Y Planner one.
#+END_QUOTE

Okay. Let's see. I can focus on making either a geek hoodie or a geek
 bag, and then move on from there.

Hmmmm.

I know people who have silkscreened stuff.

Heck, I stenciled a shirt in grade school. And it turned out quite
 good, too.

I should be able to do it again, but this time, cooler.

I should learn how to silkscreen. That'll probably be easier once I
figure out how to get frames sorted out...
