#+TITLE: Paper inbox planner

July 26th, 2005 -
[[http://sachachua.com/blog/p/2849][http://sachachua.com/blog/p/2849]]

[[http://www.douglasjohnston.net/weblog/archives/2005/07/24/planner-inbox/][The
Paper Planner Inbox]] is a good post about
 keeping an “inbox” section in your planner.

My index cards used to be my inbox as well as my semi-persistent
 storage, but now I need something with a bit more order. I really like
 my calendar, and if I can find a small six-ring planner with weekly
 forms that also have day and week goals, I'd buy it in a jiffy. I'm
 also interested in getting a six-ring puncher. Must find a large
 stationery store...

ÃƒÂ§Ã‚Â?Ã‚Â«ÃƒÂ§Ã‚Â?Ã‚Â½ÃƒÂ£Ã‚Â?Ã‚Â§ÃƒÂ¥Ã‚Â...Ã‚Â¨ÃƒÂ£Ã‚Â?Ã‚Â¦ÃƒÂ£Ã‚Â?Ã‚Â®ÃƒÂ£Ã‚Â‚Ã‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â”ÃƒÂ£Ã‚ÂƒÃ‚Â¥ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â‚Ã‚Â¿ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚ÂƒÃ‚Â‡ÃƒÂ£Ã‚Â‚Ã‚Â¤ÃƒÂ£Ã‚Â‚Ã‚Â¹ÃƒÂ£Ã‚Â‚Ã‚Â¯ÃƒÂ£Ã‚Â?Ã‚ÂŒÃƒÂ©Ã‚Â§Ã‚Â„ÃƒÂ§Ã‚Â›Ã‚Â®ÃƒÂ£Ã‚Â?Ã‚Â«ÃƒÂ£Ã‚Â?Ã‚ÂªÃƒÂ£Ã‚Â?Ã‚Â£ÃƒÂ£Ã‚Â?Ã‚Â¦ÃƒÂ£Ã‚Â?Ã‚Â---ÃƒÂ£Ã‚Â?Ã‚Â¾ÃƒÂ£Ã‚Â?Ã‚Â£ÃƒÂ£Ã‚Â?Ã‚ÂŸÃƒÂ¦Ã‚Â™Ã‚Â‚ÃƒÂ£Ã‚Â€Ã‚Â?ÃƒÂ¤Ã‚Â¼Ã‚ÂšÃƒÂ§Ã‚Â¤Ã‚Â¾ÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ£Ã‚Â‚Ã‚Â‚ÃƒÂ£Ã‚Â?Ã‚Â†ÃƒÂ£Ã‚Â?Ã‚ÂŠÃƒÂ¦Ã‚Â‰Ã‚Â‹ÃƒÂ¤Ã‚Â¸Ã‚ÂŠÃƒÂ£Ã‚Â?Ã‚Â'ÃƒÂ£Ã‚Â?Ã‚Â®ÃƒÂ§Ã‚ÂŠÃ‚Â¶ÃƒÂ¦Ã‚Â³Ã‚Â?ÃƒÂ£Ã‚Â?Ã‚Â
ÃƒÂ£Ã‚Â?Ã‚Â£ÃƒÂ£Ã‚Â?Ã‚ÂŸÃƒÂ£Ã‚Â€Ã‚Â‚ The company was really up shit
creek when a fire destroyed all their computer discs.

On Technorati: [[http://www.technorati.com/tag/organizer][organizer]]
