#+TITLE: Sprinting

September 11th, 2005 -
[[http://sachachua.com/blog/p/2972][http://sachachua.com/blog/p/2972]]

I really wanted to spend today with Mom, but I realized that I needed
 to prepare for the start of school. My mom (being an absolutely cool
 and wonderful mom) went ahead with her plans to visit the zoo with one
 of the Canadians we hosted three years ago, and I spent the day going
 through my high-priority tasks.

Planner really helped keep me on track. I started the day by listing
 all of the things I needed to do in order to prepare for the next two
 days. I arranged them so that I'd be doing related things together,
 and I set times. Then I just plowed through the tasks. Fun!

Some thoughts:

- I need an audio timer. I can probably use my computer for this.

#+BEGIN_QUOTE
  Extra points if I can get it to automatically pick up the details
   from my planner page. This might be good for remind or appt.el...
#+END_QUOTE

- Suggested review questions are very good for active reading.

#+BEGIN_QUOTE
  Unfortunately, my enggpsych text doesn't have them. I currently
   write down my notes on an index card and re-encode them as part of a
   mindmap. I should write myself review questions for flashcard-style
   or fill-in-the-blanks reviews.
#+END_QUOTE

- As a teaching assistant, I can skim the text looking for important

#+BEGIN_QUOTE
  points. I don't need to score 100% on tests. I just need to find
   ideas to tie into lab exercises.
#+END_QUOTE

- I'm running into some problems with my Toastmasters speech on

#+BEGIN_QUOTE
  introductions. I initially imagined it with a strong
   personal-coaching slant, plenty of passion, that sort of delivery.
   Thinking about it a bit more, though, I don't think I should sell
   the idea so strongly, given the fact that the audience is older and
   more experienced than I am. I'm currently favoring an advice-seeking
   approach telling my own story instead of focusing on what people
   should do.
#+END_QUOTE

- I should work on finding a note-taking style that fits me. I'm

#+BEGIN_QUOTE
  moving away from paper again because my 8.5″x11″ binder is a bit too
   big and heavy. I \_might\_ use index cards to capture diagrams and
   notes that I can't easily describe.
#+END_QUOTE

