#+TITLE: Turkey thanksgiving and Planner evangelization

October 9th, 2005 -
[[http://sachachua.com/blog/p/3058][http://sachachua.com/blog/p/3058]]

It took me \_two hours\_ to finish dinner. Not because I had heaps and
 heaps of turkey, but because halfway through what had been a very
 quiet dinner, I got into a lively discussion with the person seated
 across me.

It all started with me mentioning Google Desktop and how much I wanted
 to tinker around with stuff like that. Google Desktop sparked Danilo's
 interest, and he asked if I used it. I told him I couldn't because
 it's Windows-only. We then got into a friendly debate about open
 source and piracy. (I think piracy is evil not because it hurts big
 companies but because it makes people too lazy to look for good open
 source alternatives, which means open source developers have fewer
 users and supporters.) Then, as all extended discussions with me tend
 to become, I ended up talking about Emacs and
 [[http://www.plannerlove.com][Planner]]...

Somewhere along the way, Danilo asked me if I thought Planner could be
 good for \_everyone.\_ I told him Planner didn't have to fit
\_everyone.\_
 It just had to fit one person at a time. =) Viva open source!

I can't help it! I get really, really excited about personal
 information management, and it \_just\_ so happened that Danilo and
 Carlos were frustrated with the way they're managing their tasks and
 schedules, and I have so much fun finding or tailoring tools to fit
 people, and... <blush> ... and I talk too much when I'm excited
 about something. I was practically bouncing up and down. To think that
 I hadn't even gotten to dessert, so I couldn't blame it on a sugar
 rush!

Everyone else finished dinner and left; we were still there chatting
 about personal information management. First the other chairs were put
 away. Then the residence assistants asked if they could remove the
 tablecloth. Then they asked us to put away the table and the chairs
 eventually. By the time Blago came in to set the coffee tables for the
 next event, I knew it was time to gulp down the rest of my meal.
<laugh&ght;

Mike Tsang was just laughing at me throughout the whole thing. He knew
 I'd end up talking about Emacs and Planner at some point. <grin>

Danilo plans the way I do at the moment: scheduled tasks. He was
 really frustrated by the lack of commercial tools that allow you to
 properly schedule tasks onto a calendar. I can't wait to show him
 Planner. I hope it can fit him perfectly. =) I haven't run into any
 other tool that really supports the kind of planning I do, and I'm
 still trying to figure out how to support it on paper. But Planner is
so cool!

Carlos is a paper person, so maybe the
 [[http://www.diyplanner.com][D*I*Y Planner]] stuff will be useful for
 him. His main problem right now is that his calendar doesn't give him
 enough space to do things, and he's spread things out over three
 different calendars. I wonder what mix of forms would be good for
him...

Wheee! Really, we're onto something \_really\_ cool here with Planner
 and insane personalization... I \_really\_ \_really\_ want to get these
 ideas out into the rest of the world. Universal hyperlinking. Extreme
 customization. Zero-distraction work. And lots and lots and lots of
 fun. =D
