#+TITLE: Tips for time management

October 6th, 2005 -
[[http://sachachua.com/blog/p/3049][http://sachachua.com/blog/p/3049]]

Jessie and I also talked about the challenges of balancing the demands
 of research, studies, teaching, and life. She wanted to do an hour of
 exercise a week, but simply couldn't find the time for it. She felt
 overwhelmed with the things she needed to do.

I want to help her figure out how to gain control of her time. =) I
 sent her these tips to help her get started.

- Keep track of your time. For one week, write down everything that
 you do and how long it takes you to do it. You'll get an idea of where
 you're spending too much time and what you're not spending enough time
 on.

- Think about your priorities. What do you want to do with your life?
 Start from that and plan what you want and need to do this week.
 Schedule time in to work on things that are important to you. Then you
 can go through each day knowing that you've not only worked on the
 things that other people need you to do, but also the things that you
 want to do.

- Make the most of your time. Is whatever you're doing something you
 really need to do? Can you invest a little time in the beginning to
 save more time later on?

I have a spare academic planner that I'm no longer using because I
 have my own system for keeping track of my time. I'm thinking of
 giving it to her because I'm not using it anyway. =)

I'm also thinking of doing D*I*Y planner templates to help people do
 that kind of time analysis...
