#+TITLE: National novel-writing month? Try paper-writing week!

November 24th, 2005 -
[[http://sachachua.com/blog/p/3156][http://sachachua.com/blog/p/3156]]

I've convinced myself that it will actually be possible to write the
 two major papers due first week of December within the time I have
 left. It's just going to take some very, very careful planning and
 lots of determination. Fortunately, I've gotten used to thinking and
 writing in a hurry. (Hooray for programming contests! Hooray for open
 source! Hooray for lab reports and magazine articles!)

For my reading course, I'll focus on how people organize and share
 files. I'll go deeply into that one first, and then if I manage to
 follow my schedule, I \_might\_ have some time to add detail about
using
 tags to organize bookmarks and e-mail. I need a paper that degrades
 gracefully depending on the time I have left to write it, and I need
 to make sure it makes the most of the references I already have. Hey,
 if I focus on tagging files, I get to use the snippet-related stuff I
 started reading about before! Isn't it nifty how things come together?

For my engineering psychology course, I've already figured out the
 points I wanted to highlight. I need to sit down and plow through
 them, adding insights from the decision-making models we're taking up
 now. Again, for that one: slow and systematic.

To make life easier for me, I'll make my On Campus submission
 something I can speak about easily. I think I'll write about the brain
 drain / brain gain thing, as that's something I can get on my soapbox
 about. I need to make sure I haven't already written about it. Then
 again, I can also write about programming competitions or open source.

For D*I*Y Planner, I can write about scheduling all of my cramming.
 Maybe there's some way I can turn it into a D*I*Y Template story. Or I
 can warn Doug now... Right, I should do that so at least I'm safe for
 the next two weeks. Sent the message.

At some point I need to write a personal statement for the
 scholarship. The deadline for that is the 15th, so I have some time,
 but I should ask professors for references before they get swamped
 with end-of-term work. It's a little bit late, but I hope I can make
 it.

I'm probably going to go quiet for the next few weeks. If you don't
 see the occasional blog post in my RSS feeds, don't worry, it's not
 due to frostbite. At least I hope not. That would totally suck,
 particularly as I have paragraphs and paragraphs to write before I
 sleep. ;)

Today was \_really\_ cold and windy, though. If you remember the polar
 scene from Madagascar---yeah, something like that. I learned two
 things: (a) I'm light enough to find it hard to fight against the
 wind, and (b) walking backward is sometimes easier than walking
 forward, particularly when going against the wind in a long coat with
 a good hood. Must be careful about cars and streets.

Just one extracurricular thing for next week: the tango thing. I don't
 think I'll go to Toastmasters (even though it's the elections, meep),
 and I won't be going to improv comedy next week either. Must write
 write write... =)

Oooh, this'll be fun. =D
