#+TITLE: Productive day!

June 2nd, 2005 -
[[http://sachachua.com/blog/p/2772][http://sachachua.com/blog/p/2772]]

I had so much fun writing today. 500 words for my m-ph entry, 1000 for
 the Linux Journal article on taming the todo (okay, I wrote maybe half
 of that last week), and 55 for the short story “Gluttony”. I e-mailed
 the people I was supposed to e-mail from the game journalists' meet. I
 also released another version of Planner (3.30) and started setting up
 better version control.

WHEW!

\_And\_ I got to bond with my dad this morning, too. We looked for
 music. Couldn't find any decent musicals at Music One. They had the
 movie soundtrack for Phantom of the Opera, but I want the Broadway
 version because Raoul sounds like such a wuss in the movie. ;) Time to
 look for Rent, Cats, and all of those other musicals...

ÃƒÂ§Ã‚Â§Ã‚Â?ÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ£Ã‚Â?Ã‚Â“ÃƒÂ£Ã‚Â?Ã‚Â®ÃƒÂ£Ã‚Â‚Ã‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â”ÃƒÂ£Ã‚ÂƒÃ‚Â¥ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â‚Ã‚Â¿ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â?Ã‚Â«ÃƒÂ§Ã‚Â²Ã‚Â¾ÃƒÂ©Ã‚Â€Ã‚ÂšÃƒÂ£Ã‚Â?Ã‚Â---ÃƒÂ£Ã‚Â?Ã‚Â¦ÃƒÂ£Ã‚Â?Ã‚Â„ÃƒÂ£Ã‚Â‚Ã‚Â‹ÃƒÂ£Ã‚Â€Ã‚Â‚
I am familiar with this computer.

On Technorati: [[http://www.technorati.com/tag/writing][writing]]
