#+TITLE: Five lessons learned from last week

July 25th, 2005 -
[[http://sachachua.com/blog/p/2846][http://sachachua.com/blog/p/2846]]

-  Research groups are good. The lively exchange of ideas will inspire
    and support me, and besides, group meetings often have food. It's
    worth postponing my individual interest in personal information
    management if I can't find other people who are working on the same
    area.
-  I'm good at networking and relating to people quickly. I'm still a
    little shy, but I'm starting to be good at remembering names and
    faces, and people here don't mind helping someone get settled in.
-  A personal organizer makes me feel more on top of things. If I can
    find a ring-bound paper organizer with the same structure as my
    current planner, I'll switch to it. I really appreciate having
    weekly and daily goals, and might prepare my own templates if I
    can't find an organizer that normally does that.
-  I can write 800 words easily once I get going. I prefer writing in
    one go instead of filling out an outline because the former feels
    more like writing e-mail to someone, and I can get pretty
    long-winded in e-mail.
-  My writing style seems to be matter-of-fact and conversational.
    Dominique thinks I've found my voice.

ÃƒÂ¨Ã‚Â¿Ã‚Â‘ÃƒÂ¥Ã‚Â¹Ã‚Â´ÃƒÂ£Ã‚Â?Ã‚Â§ÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ£Ã‚Â€Ã‚Â?ÃƒÂ©Ã‚Â›Ã‚Â»ÃƒÂ¥Ã‚Â­Ã‚Â?ÃƒÂ£Ã‚Â‚Ã‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â”ÃƒÂ£Ã‚ÂƒÃ‚Â¥ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â‚Ã‚Â¿ÃƒÂ£Ã‚Â?Ã‚ÂŒÃƒÂ£Ã‚Â?Ã‚Â¾ÃƒÂ£Ã‚Â?Ã‚Â™ÃƒÂ£Ã‚Â?Ã‚Â¾ÃƒÂ£Ã‚Â?Ã‚Â™ÃƒÂ©Ã‚Â‡Ã‚Â?ÃƒÂ¨Ã‚Â¦Ã‚Â?ÃƒÂ£Ã‚Â?Ã‚Â«ÃƒÂ£Ã‚Â?Ã‚ÂªÃƒÂ£Ã‚Â?Ã‚Â£ÃƒÂ£Ã‚Â?Ã‚Â¦ÃƒÂ£Ã‚Â?Ã‚Â?ÃƒÂ£Ã‚Â?Ã‚ÂŸÃƒÂ£Ã‚Â€Ã‚Â‚
In recent years electronic computers have become increasingly important.

On Technorati: [[http://www.technorati.com/tag/writing][writing]],
[[http://www.technorati.com/tag/organizer][organizer]],
[[http://www.technorati.com/tag/research][research]]
