#+TITLE: How I use my Hipster PDA

May 8th, 2005 -
[[http://sachachua.com/blog/p/2753][http://sachachua.com/blog/p/2753]]

After all my experiments with
[[http://sachachua.com/notebook/wiki/WearableComputing][wearable
computing]]
 using a [[http://www.handykey.com][one-handed chording keyboard]] and a
[[http://www.speech.cs.cmu.edu/flite/][speech synthesizer]],
 I've found that the most portable device for me is still a 3×5 pack of
index cards bound with a fold-back clip.
 Jokingly dubbed the “Hipster PDA” elsewhere on the Net, this low-tech
device is surprisingly flexible and easy to use.
 I use mine to keep track of tasks and random notes for later entry into
my online planner.

My Hipster PDA is composed of:

-  a colored index card with my contact information
-  my inbox: cards with notes on them that haven't been entered into the
   computer
-  two pages of month templates from a 3×5 day planner
-  a year calendar for 2005 and 2006
-  my archive: index cards that have already been entered but might
   still be useful
-  a colored index card with yellow sticky notes
-  a stack of blank index cards
-  a fold-back clip holding all of these things together
-  a black signpen or a mechanical pencil tucked into the fold-back clip

One of the things I've found much easier to do with my 3×5 pack of
 cards than with a PDA or a Franklin-Covey planner is to keep track of
 get-togethers. When my friends and I schedule our next get-together, I
 lay the month templates out so that I can see the next 30 days at a
 glance. This is difficult to do with a PDA because PDA screens are
 small. A Franklin-Covey planner would probably be more organized, but
 I like being able to lay things out side-by-side instead of flipping
 through pages.

When I need to jot something down, I flip the deck and write on the
 last card. After I finish one side of the card, I turn it over, clip
 it, and write on the other side. When the whole card is full, I move
 it into my inbox.

Index cards are handy because it's easy to give information away to
 other people. Paper gets crumpled and business cards can disappear
 into the chaos of a purse or a bag. An index card is big and bright.
 I'm thinking of replacing half of my white cards with brightly-colored
 cards so that people can easily find information I give them.

I'm planning to do other things with my pack of 3×5 index cards. For
 example, I can write my projects on the cards. Reviewing these cards
 will reinforce these goals in my mind and remind me to keep making
 progress.

Index cards totally rock.

ÃƒÂ¦Ã‚Â--Ã‚Â°ÃƒÂ£Ã‚Â?Ã‚Â---ÃƒÂ£Ã‚Â?Ã‚Â„ÃƒÂ£Ã‚Â‚Ã‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â”ÃƒÂ£Ã‚ÂƒÃ‚Â¥ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â‚Ã‚Â¿ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ¦Ã‚Â---Ã‚Â§ÃƒÂ¥Ã‚ÂžÃ‚Â‹ÃƒÂ£Ã‚Â‚Ã‚ÂˆÃƒÂ£Ã‚Â‚Ã‚ÂŠÃƒÂ£Ã‚Â‚Ã‚Â‚ÃƒÂ¯Ã‚Â¼Ã‚Â‘ÃƒÂ¯Ã‚Â¼Ã‚Â?ÃƒÂ¥Ã‚Â€Ã‚Â?ÃƒÂ©Ã‚Â€Ã‚ÂŸÃƒÂ£Ã‚Â?Ã‚Â„ÃƒÂ£Ã‚Â€Ã‚Â‚
The new computer is ten times as fast as the old one.

On Technorati:
[[http://www.technorati.com/tag/productivity][productivity]],
[[http://www.technorati.com/tag/planning][planning]],
[[http://www.technorati.com/tag/hipster][hipster]],
[[http://www.technorati.com/tag/hipsterpda][hipsterpda]],
[[http://www.technorati.com/tag/organizer][organizer]]
