#+TITLE: Hipster PDA: Waste of paper?

June 16th, 2005 -
[[http://sachachua.com/blog/p/2777][http://sachachua.com/blog/p/2777]]

An insightful but anonymous person wrote in:

#+BEGIN_QUOTE
  Not sure if anyone else has mentioned this, but even though the
   HipsterPDA is excellent for notetaking etc., it really is a waste of
   paper!

  “My notes and to dos are NOT a waste” I hear you cry. But that's not
   what I'm referring to. I'm referring to using ONE index card for
   writing a phone number, or an address, or a task. When this
   information is then transferred to the necessary electronic or paper
   area, the card is thrown in the trash -- what a waste!

  I apologise to those of you who recycle your cards, but from the many
   articles, comments I've read re: HipsterPDA, most people just trash
   the card and that's it.

  I'm not a great fan of the digital world, but this disrespect for
   paper (and ultimately the rainforests) is just not on.
#+END_QUOTE

Hmm. Good point. Index cards require more processing than cheap paper
 notebooks do. I like the feel of heavy paper, and index cards require
 more chemicals and raw material than paper notebooks do.

I use one index card for all my notes regarding a meeting (and
 sometimes two if I need to segregate topics or spill over). I throw
 the card away after I get the data into my Planner. I don't really use
 my index cards for keeping track of tasks, as most of my tasks so far
 have been computer-related. My deck of index cards is really more for
 jotting down notes, making quick sketches, or giving information to
 other people.

I feel the trade-off is justified. I work better with index cards. A
 pack of 100 or 500 index cards is a small price to pay if it helps me
 keep track of things I should do or little nuggets of information I
 should pass onto other people.

Even if you multiply that by all the billions of people in the world,
 as long as they use their index cards to help themselves keep track of
 things worth keeping track of, then I think that's a net win for the
 earth.

Conservation is important, but it is not enough to see the evil in
 little things. We make a lot of choices that cost the environment.
 Food. Clothes. Housing and furniture. Should we stop eating because
 cooking by gas or electricity uses a lot of energy from non-renewable
 sources and the amount of waste going on in fast food places and
 restaurants is staggering? Should we stop patronizing bookstores
 because the vast majority of books don't get read and reused? Should
 we take our fingers off our keyboards now in protest against the way
 computers contribute to environmental problems? Should we take direct
 steps to end the world's population problem? We make choices.

In this case, I think my pack of index cards is certainly worth it. I
 respect paper, which is why I write down things that are worth writing
 down. I respect trees. I really, really like trees, and wish we had
 more in the city.

After I fill up the card and store it somewhere, I won't be able to
 use it a lot. I could write on my cards with a pencil and erase my
 writing until the card falls apart, but my time and the earth's time
 isn't worth that.

It's good to look for ways to save the environment. Reduce, reuse and
 recycle. However, don't lose sight of the forest for the trees. Little
 things matter, but if they help you do better things, then maybe it's
 worth it. You just need to make sure that what you're doing is worth
 the cost.

It's one more thing to add to the pile of recyclable material (not
 that garbage is really segregated in this country), one more problem
 contributing to the death of the earth, but it's something I choose to
 use. Not that this is going to convince hard-core environmentalists
 that I'm not a selfish, evil person, but at least I know and take
 responsibility for my choice.

E-Mail from Richi's server

On Technorati: [[http://www.technorati.com/tag/hipsterpda][hipsterpda]],
[[http://www.technorati.com/tag/hipster][hipster]],
[[http://www.technorati.com/tag/rant][rant]]
