#+TITLE: Emacs: It's all about people

November 9th, 2005 -
[[http://sachachua.com/blog/p/3132][http://sachachua.com/blog/p/3132]]

Kathy Sierra of Creating Passionate Users quotes Nat Torkington: “It's
 no longer aspergers and emacs... we're putting people back into the
 equation.”

Why do people like bashing Emacs so much? Why do even geeks pooh-pooh
 it as a text editor that's too complicated for its own good?

If you just want a plain text editor, Emacs is really easy to learn.
 Just start up a graphical version of Emacs and you've got menus and
 toolbars that can help you start editing right away. I think this is
 more of an image problem than anything else. It's like the way people
 say, “Linux is too hard to learn!” Linux isn't hard to learn; you just
 have to try it. Emacs isn't hard to learn; you just have to try it.

What probably intimidates people, though, is the knowledge that
 there's so much more out there. There's so much potential. Once you
 know how to use gedit or vim, that's pretty much it. Everything else
 is just about shortcuts. But Emacs... the more you learn about Emacs,
 the more there is to learn about Emacs.

Richi Plana wrote:

#+BEGIN_QUOTE
  My only problem with it is that it doesn't seem to be
   designed to be self-learnable. It requires trundling for
  documentation
   and, more than that, asking people. In a sense, it's passed on from
   generation to generation by word-of-mouth.
#+END_QUOTE

And I \_love\_ that! I love the fact that when you really get into
 learning how to use Emacs, you can't help but get hooked up with all
 these other people. I love the fact that when I download Emacs
 extensions, I'm getting an idea of how other people made their Emacs
 fit them better.

Emacs is the most user-friendly application I've ever used. I'm not a
 typical user. I \_like\_ hacking my editor. I tweak it every so often,
 whenever I want to procrastinate doing something else. I \_love\_ how
 Emacs invites me to change it, to make it my own. In Emacs, source is
 not sacred! I can change anything I want about Emacs. I can make it
 fit \_me\_ instead of having to fit it. Emacs gives me all the tools to
 do that and all the source code I need.

I also like tweaking programs for other people, and that's another way
 that Emacs is just so wonderfully user-centered. I love how I can make
 Emacs be so many things to so many people. I've made it into a
 Japanese-vocabulary flashcard game for a coworker. I've made it a
 planner for a non-geek friend. I've even used it as a Tetris game!
 Emacs lets me help other people by tweaking the code that's already
 out there to fit the people I know, and I think that's absolutely
wonderful.

For me, Emacs is inherently social. Emacs really transformed my
 experience of free software and open source, hooking me up with all
 these awesome communities. Unlike the bare and merely functional
 configuration files I have for other programs, my Emacs configuration
 files say something about who I am, what I like, and how I think. And
 \_that's\_ why I can't help but gush about it all the time. It's
 something so different from any other open source project I've ever
 tried.

I want to learn how to explain this mindblowingly awesome difference
 to other people. We've got nongeeks learning Emacs. They're fantastic!
 They've never heard about Emacs. They aren't scared of it. They just
 happened to see one of their friends using Planner or whatever, and
 they wanted to try it out. Isn't that cool?

So yeah, Emacs is all about people. Other geeks may put it down, but
 it spreads because of word of mouth anyway. It's really awesome, and
 one day I'm going to figure out how to describe just why it's
awesome...

-  [[http://headrush.typepad.com/creating_passionate_users/2005/11/creating_happy_.html][Read
   Kathy Sierra: Creating happy programmers]]
-  [[http://sacha.free.net.ph/notebook/wiki/2005.11.09.php?show_id=2005-11-09-1#a31313a3230616d][Read
   Richi's comment on my previous blog entry]]
-  [[http://www.emacswiki.org/cgi-bin/wiki?GnuEmacs][Emacswiki.org page
   about GNU Emacs]]

