#+TITLE: Working with Emacs

July 1st, 2005 -
[[http://sachachua.com/blog/p/2804][http://sachachua.com/blog/p/2804]]

A recent post on the Philippine Linux Users' Group suggested a
 separate plug-emacs mailing lists for all the Emacs messages that have
 popped up recently. The suggester said:

#+BEGIN_QUOTE
  There is a
   difference between discussion and stroking each other's ego. :)
#+END_QUOTE

Working with Emacs is a humbling experience. It brings you face to
 face with accumulated centuries of developers' work. Emacs involves
 people in its development to an unusual extent. Working with vi and
 even Eclipse made me feel more like a user than a co-developer.
 Working with Emacs made me feel part of the community, even when I was
 still struggling to make sense of the parentheses.

If in that sense, Emacs worship is considered ego-stroking, then sure,
 I'm guilty. I can't help but express my appreciation for one of those
 things that has really changed my life and made free, open source
 software really meaningful to me. For the culture, really, that made
 it possible. It's a piece of software, but it's also a conversation
 with so many developers around the world.

To newbies: if you're curious about the thrills of open source
 development and you want a nice, easy way to get started, why not try
 modifying Emacs? It's easy to pick up. All the source code is there,
 and you can modify it on the fly. We've had complete non-programmers
 try it out and fall in love with programming. They get thrilled when
 they share their tweaks and other people respond with comments and
 suggestions. This is good stuff. Try it out. =)

I suppose Emacs is off-topic. After all, it's cross-platform, not
 Linux-specific. I could easily be extolling the wonders of Emacs on
 Mac OS X, Microsoft Windows, or BSD. Emacs doesn't require Linux.
 (Neither does Apache, but you don't see people waxing lyrical about
 web servers that often, do you?) The flood of Emacs-related posts that
 deluge the list whenever someone unwittingly brings up the topic is
 probably incomprehensible to people who've never tried Emacs or tried
 Emacs as just an editor and didn't like it.

Still, I want to share what makes open source real for me. Not kernel
 hacking, which is still too intimidating despite the existence of
 projects like kernel-janitor. Not network or system administration,
 which I don't have the patience to do. Just the free and flexible
 customization of something I use everyday and the thrill of sharing
 these customizations with other people in a community that spans the
 world.

I guess that's why I post on PLUG instead of plug-misc. I don't think
 PLUG should just be a venue for asking and answering technical
 questions, but also for sharing nifty hacks and examples of how far a
 Linux system can be pushed. Other people push their systems in terms
 of hardware and services. I push mine in terms of how well it can fit
 me, how well it can anticipate my needs.

I want to stroke other people's egos. I want people to discover how
 they can contribute to free and open source software, to experience
 the thrill of seeing their code out there and being used. Open source
 development isn't just for PHP wizards or C freaks who can contribute
 to existing projects or launch an entirely new project on their own.
 Maybe---just maybe!---people who thought themselves just users of a
text
 editor will be inspired to think about how they can start customizing
 their own.

ÃƒÂ£Ã‚Â‚Ã‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â”ÃƒÂ£Ã‚ÂƒÃ‚Â¥ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â‚Ã‚Â¿ÃƒÂ£Ã‚Â‚Ã‚Â'ÃƒÂ¤Ã‚Â½Ã‚Â¿ÃƒÂ£Ã‚Â?Ã‚ÂˆÃƒÂ£Ã‚Â?Ã‚Â°ÃƒÂ¦Ã‚Â™Ã‚Â‚ÃƒÂ©Ã‚Â--Ã‚Â“ÃƒÂ£Ã‚Â?Ã‚Â«ÃƒÂ§Ã‚Â¯Ã‚Â€ÃƒÂ§Ã‚Â´Ã‚Â„ÃƒÂ£Ã‚Â?Ã‚Â«ÃƒÂ£Ã‚Â?Ã‚ÂªÃƒÂ£Ã‚Â‚Ã‚Â‹ÃƒÂ£Ã‚Â€Ã‚Â‚
Computers will save you a lot of time.

[[http://www.livejournal.com/~eclair/][clair ching says:]]

#+BEGIN_QUOTE
  I can't help but agree with you. Emacs is the way that I
   appreciated FOSS more compared to GNU/Linux per se. Why? It's because
   I easily felt part of the community of Emacs users and hackers on the
   Emacs Wiki. That kind of interaction makes it less scary for newbies,
   IMHO. I mean, not all people on the Emacs Wiki are very friendly, I
   suppose, but the ones I have interacted with as I was learning to use
   various tools and modes available showed me that I can do something
   for the FOSS community, which is to write about what I learn. I don't
   even know ELISP but at least I know that my blog entries are helpful
   to others too. =)

  I guess we have been too giddy over Emacs on the PLUG mailing list
   that is why someone suggested that. Well, I know I have always been
   giddy about it but I can't help myself! \^\_\^ Emacs is wonderful...

  Besides there are so many hacks in Emacs that make FOSS usage,
   learning and advocacy so much fun! Like the Planner mode that allows
   me to somewhat organize my life, my thoughts, my schedule. Eshell
   allows me to do some things without opening a separate terminal. In
   Planner, I also store my notes on advocacy and my blog entry drafts.
  I
   also listen to music on Emacs. And when something goes wrong on
   whatever mode I am using, I can email the maintainer immediately, to
   tell him/her what happened so that the bug can be fixed, etc. I try
  to
   be as detailed as possible when I do that. So I guess that is my
   contribution. =)

  In any case, I also enjoy the company of people using Emacs, not just
   because we talk about Emacs but because I am learning so much about
   you guys =)
#+END_QUOTE

On Technorati: [[http://www.technorati.com/tag/opensource][opensource]],
[[http://www.technorati.com/tag/development][development]],
[[http://www.technorati.com/tag/emacs][emacs]],
[[http://www.technorati.com/tag/soapbox][soapbox]],
[[http://www.technorati.com/tag/advocacy][advocacy]]
