#+TITLE: Reflections on 2005

December 29th, 2005 -
[[http://sachachua.com/blog/p/3215][http://sachachua.com/blog/p/3215]]

This year saw me in three countries: Japan, Philippines, and Canada.
 On the surface level, I learned about a fair number of things: Jakarta
 Struts, Ruby, engineering psychology and human performance...

Other things I learned:

-  *I love writing.* One article in the Linux Journal resulted
    in dozens of e-mail. My column in Computerworld On Campus got a lot
   of
    feedback from students whose lives I'd touched (even if only
   lightly).
    My weekly posts on diyplanner.com get feedback, too. I love writing.
   I
    can affect people through it. What took me so long?
-  *I need people.* This was the year that my current barkada
    really came together. The year started with the Digital Pinay
   fiasco,
    which was how Clair and I really got to know each other. The year
   also
    saw Slycesoft developments and our little triumphs and crises. I'm
    also very glad I have Dominique and my family. =) With them, the
    future looks even better.
-  *I have much, much more to learn about the working world.*
    If I could do one thing over this year, it would be that span
    of time at a company in Cebu. Looking back, I can see how I could've
    been more politically sensitive. It was a valuable lesson, and one
    I'll keep in mind.
-  *I want---no, \_need\_---to make a difference.* =)

My biggest challenge for 2005: graduate school

My biggest challenge was adapting to graduate school. I found it
 difficult to be motivated and confident. I had a really bad attack of
 the impostor syndrome that made me almost quit my teaching
 assistantship because I felt I was doing the students such a
 disservice by teaching something I didn't really know. The students
 reassured me, my professor and the previous teaching assistant helped
 me, and even the assistant department chair called me in and
 half-scolded, half-encouraged me.

The engineering psychology and human performance class was
 interesting, too. The lab reports really helped me review statistics,
 and I enjoyed writing. If I could do one thing differently, I wish I
 had kept my new-found study habits instead of getting frustrated in
 lectures. I used to read ahead, but I found it difficult to pay
 attention in class, so I ended up just reading afterwards. Maybe
 graduate-oriented classes will be more engaging.

Searching for a good project was also very difficult. My research
 supervisor and I went through so many ideas. Because I didn't have a
 clear research question in mind, I felt adrift and frustrated. I
 wasn't sure if graduate school was worth the opportunity cost. I'm
 happy now, though. We've found something that not only fits in with
 our short- and medium-term goals, but also helps me with my long-term
 goals. I think social search provides interesting possibilities,
 particularly if we can make it much easier to do, much more
 mainstream. I'm curious about whether we can make it easy to filter by
 multiple networks, too. I still feel a little guilty about not having
 completed my reading paper, but I resolve to turn in an absolutely
 wonderful one next term! =)

I think the secret to life is being fully in the present, wherever I
 am. I'm looking forward to throwing myself into the metadata course
 when I get back to Canada, and I'm setting aside time to read papers
 while on vacation.

Best memories for 2005

Listening to my family's stories. Chasing horses and ice cream carts
 while learning photography. Hanging out with my friends. Geek lurv.
 (Hi Dominique! Hi Clair and JM! Hi Paolo and Kris! Hi Marcelle and
 Gin! ;) ) Digital Pinay smackdown. Long phone calls and Skype
 sessions. Cryptograms. Graduate House people and activities. New
 friends and old friends. =)

Goals for 2006

-  *Read more.* I want to read at least a book a week and a
    scholarly paper a day.
-  *Write more.* I want to write a scholarly paper. I want to
    continue writing articles for magazines. I want to post thoughtful
    pieces on my blog more often. =)
-  *Study more.* I want to make my department glad they took a
    chance on me. =)
-  *Do more.* I want to lay the groundwork so that I have an idea of
    what to do after my master's degree.
-  *Live more.* I want to make more friends in the Philippines and
    in Canada. I want our barkada to grow---fresh blood! =)---and I want
   to
    find a group of people I can hang out with in Canada.
-  *Be more.* I want to make a difference (even a small one!) at
    least every week.

On Technorati:
[[http://www.technorati.com/tag/reflections][reflections]]
