#+TITLE: Wahoo! iPod Photo

June 1st, 2005 -
[[http://sachachua.com/blog/p/2768][http://sachachua.com/blog/p/2768]]

So much for not being a gadget freak. =)

Dad got me an iPod Photo (30GB). After I formatted it to FAT32 using
Windows, it mounted easily under Linux.
 I used the excellent
[[http://sachachua.com/notebook/emacs/bbdb-vcard-export.el][bbdb-vcard-export.el]]
to export my address book to lots and lots of VCF files, which I then
copied into the iPod Photo.

I downloaded a couple of speeches and podcasts for my spiffy new iPod.
 I'm looking for audio books and poetry. Would anyone have a freely
 distributable archive of Shakespearean sonnets in MP3 form? If not,
 I'll probably try using a synthesizer to make instant e-books, or I
 can record them a poem or two at a time...

Downside? Adding new photos requires iTunes, which means I need to use
 either Windows or a Mac. I guess I'll really be bringing the Vaio with
 me.

Also, I'm really looking forward to
 [[http://www.ipodlinux.org][ipodlinux]] fully supporting the iPod
 Photo. I'd love to run Linux on the device! I need to figure out how
 to flash the bootloader on and how to recover from mistakes. If I get
 that working, then I can help hack...

ÃƒÂ¦Ã‚ÂˆÃ‚Â‘ÃƒÂ£Ã‚Â€Ã‚Â...ÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ¥Ã‚Â•Ã‚Â?ÃƒÂ©Ã‚Â¡Ã‚ÂŒÃƒÂ¨Ã‚Â§Ã‚Â£ÃƒÂ¦Ã‚Â±Ã‚ÂºÃƒÂ£Ã‚Â?Ã‚Â¨ÃƒÂ¦Ã‚ÂƒÃ‚Â...ÃƒÂ¥Ã‚Â
Ã‚Â±ÃƒÂ¦Ã‚Â•Ã‚Â´ÃƒÂ§Ã‚Â?Ã‚Â†ÃƒÂ£Ã‚Â?Ã‚Â®ÃƒÂ£Ã‚Â?Ã‚ÂŸÃƒÂ£Ã‚Â‚Ã‚Â?ÃƒÂ£Ã‚Â?Ã‚Â«ÃƒÂ£Ã‚Â‚Ã‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â³ÃƒÂ£Ã‚ÂƒÃ‚Â”ÃƒÂ£Ã‚ÂƒÃ‚Â¥ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â‚Ã‚Â¿ÃƒÂ£Ã‚ÂƒÃ‚Â¼ÃƒÂ£Ã‚Â‚Ã‚Â'ÃƒÂ¤Ã‚Â½Ã‚Â¿ÃƒÂ£Ã‚Â?Ã‚Â†ÃƒÂ£Ã‚Â€Ã‚Â‚
We use computers to solve problems and to put information in order.

On Technorati: [[http://www.technorati.com/tag/gadgets][gadgets]],
[[http://www.technorati.com/tag/emacs][emacs]],
[[http://www.technorati.com/tag/linux][linux]]
