#+TITLE: Being a girl

May 31st, 2006 -
[[http://sachachua.com/blog/p/3547][http://sachachua.com/blog/p/3547]]

[[http://www.horsepigcow.com/2006/05/sometimes-being-pic-really-sucks.html][Tara
Hunt]]
 knows what it's like to fade into the background if one has a
 partner in crime. I don't really have that problem, probably because
 people are, like, “Ooh! a girl!” Kinda.

I like being a girl. I like turning up to tech conferences in dresses
 and earrings. I like hacking my computer T-shirts into something with
 more style. I like being me.

I like sneaking into tech get-togethers like the Linux Users Group or
 Ruby Users Group without worrying about technical credibility. I blend
 in. I'm part of the woodwork. People will just assume that I'm
 someone's girlfriend.

I like playing up my social aspect. I like connecting with people.
 Most people find it hard to reach out. They think it's easier for me
 because I'm a girl. Maybe it is. Maybe it isn't. Maybe I just use
 being a girl as an excuse to get over my nervousness. =)

If I have to bat my eyelashes at people and bribe them with homemade
 cookies, so be it.

If I have to jolt people out of their stereotypes by asking
 well-thought questions, I do so with great gusto.

If I have to bring out my laptop and do some console work in front of
 them to show them I've got the chops, fine.

And when the shadows in my head whisper that I'm not as good as the
 others, not as geeky as the others, I drown them in Emacs Lisp. ;)

On Technorati: [[http://www.technorati.com/tag/emacs][emacs]],
[[http://www.technorati.com/tag/girl][girl]],
[[http://www.technorati.com/tag/geekette][geekette]],
[[http://www.technorati.com/tag/geek][geek]]

Random Japanese sentence:
ÃƒÂ£Ã‚Â?Ã‚ÂŠÃƒÂ£Ã‚Â?Ã‚Â---ÃƒÂ£Ã‚Â‚Ã‚ÂƒÃƒÂ£Ã‚Â?Ã‚Â¹ÃƒÂ£Ã‚Â‚Ã‚ÂŠÃƒÂ£Ã‚Â?Ã‚Â®ÃƒÂ¤Ã‚ÂºÃ‚ÂºÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ£Ã‚Â€Ã‚Â?ÃƒÂ£Ã‚Â?Ã‚Â„ÃƒÂ£Ã‚Â?Ã‚Â¤ÃƒÂ£Ã‚Â‚Ã‚Â‚ÃƒÂ§Ã‚Â§Ã‚Â˜ÃƒÂ¥Ã‚Â¯Ã‚Â†ÃƒÂ£Ã‚Â‚Ã‚Â'ÃƒÂ£Ã‚Â?Ã‚Â°ÃƒÂ£Ã‚Â?Ã‚Â?ÃƒÂ£Ã‚Â‚Ã‚Â?ÃƒÂ£Ã‚Â?Ã‚Â---ÃƒÂ£Ã‚Â?Ã‚Â¦ÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ¤Ã‚Â»Ã‚Â--ÃƒÂ¤Ã‚ÂºÃ‚ÂºÃƒÂ£Ã‚Â?Ã‚Â®ÃƒÂ¥Ã‚ÂˆÃ‚Â©ÃƒÂ¥Ã‚Â®Ã‚Â³ÃƒÂ£Ã‚Â‚Ã‚Â'ÃƒÂ¥Ã‚Â†Ã‚Â'ÃƒÂ£Ã‚Â?Ã‚Â---ÃƒÂ£Ã‚Â?Ã‚Â¦ÃƒÂ£Ã‚Â?Ã‚Â„ÃƒÂ£Ã‚Â‚Ã‚Â‹ÃƒÂ£Ã‚Â€Ã‚Â‚
A talkative person is always letting the cat out of the bag and
jeopardizing the interests of others.
