#+TITLE: Why I like the Emacs editor

February 5th, 2006 -
[[http://sachachua.com/blog/p/3257][http://sachachua.com/blog/p/3257]]

Most editors treat everyone the same. Emacs, on the other hand, becomes
 uniquely yours -- tamed, like the fox in The Little Prince. Let me
paraphrase:

#+BEGIN_QUOTE
  “No,” said the little prince. “I am looking for friends. What does
   that mean---'customize'?”

  “It is an act too often neglected,” said Emacs. “It means to
   establish ties.”

  “‘To establish ties'?”

  “Just that,” said Emacs. “To me, you are still nothing more than a
   user who is just like a hundred thousand other users. And I have no
   need of you. And you, on your part, have no need of me. To you, I am
   nothing more than a editor like a hundred thousand other editors. But
   if you customize me, then we shall need each other. To me, you will
  be
   unique in all the world. To you, I shall be unique in all the
   world...”
#+END_QUOTE

And that is why I like Emacs. It may not be the perfect editor, but
 it's \_mine.\_ =)

On Technorati: [[http://www.technorati.com/tag/emacs][emacs]]
