#+TITLE: ‘tinerant Tuesday

February 22nd, 2006 -
[[http://sachachua.com/blog/p/3278][http://sachachua.com/blog/p/3278]]

I firmly believe that the best way to get to know a city is to wander
 around. With that in mind, I strolled around downtown Boston, picking
 up a pocket-sized fold-out map and various brochures from the Visitor
 Information Center and a bottle of Noodler's Ink from a wonderful
 little pen shop on Bromfield. I also took the opportunity to pass by
 the Free Software Foundation. RMS was out, but I met John Sullivan and
 gave him a hug for working on Planner. (I'd forgotten to bake
 gluten-free cookies for him. Oops.) I also walked around the park,
 wandered over to the public library, and bought a pattern and some
 cloth from Walmart.

Boston is pretty, with plenty of trees and beautiful brick buildings
 lining narrow, winding roads. It is thus all too easy to get lost in,
 not because the streets are difficult to locate on a map (they're
 clearly labelled) but because wandering around without any particular
 aim is so pleasant. =)

On Technorati: [[http://www.technorati.com/tag/boston][boston]]
