#+TITLE: Hot chocolate day

July 17th, 2006 -
[[http://sachachua.com/blog/p/3673][http://sachachua.com/blog/p/3673]]

It took me two hours to commute to work this morning. I needed to be
 there because my planner only had “@1300-1330 CAS workshop” on it -- no
 details, no call-in number, nothing. I didn't even know who might have
 information.

When I got to IBM, the sheer silence of CAS just descended on me. I
 felt so isolated.

One of the reasons why I'm hardly ever in the Interactive Media Lab in
 the University of Toronto is that it's just so quiet. The room I work
 in has a small window near the ceiling. John Chattoe works in the same
 room, and Mark Chignell is of course in the next office. I feel okay
 with interrupting Mark every so often when I need a social break from
 my work, but still... Also, having to prepare lunch using a microwave
 instead of cooking something quickly -- not quite as much fun! <laugh>

The working environment at the Centre for Advanced Studies is similar,
 although I feel even more isolated. The centre uses an open layout to
 encourage students to interact with each other, but we hardly ever
 talk. Maybe it's because I missed the CAS party last time. Maybe it's
 because I haven't joined any of the sports groups. I don't know.

So there I was, tired from my commute, feeling rather oppressed by the
 silence and lack of social interaction, really craving VPN (the
 ability to connect from outside IBM), and going through blog posts
 just to recapture that sense of IBM as a human organization.

And sniffling. Quietly. Over a cup of hot chocolate. (Fortunately, CAS
 had restocked hot chocolate over the weekend. Hooray for small
 miracles!)

I really appreciate how Quinn Fung joined me for lunch even though she
 wasn't particularly hungry, and how Laurie Dillon-Schalk called me up
 to check on me when she found out I was having a hot chocloate day.

Today I realized a few more things:

-  Long commutes totally don't work for me. This probably also rules
    out on-site consulting, which was one of the career options I had
    been considering.
-  I like social interaction. I don't mind working longer hours if I
    can look up and talk to people, bounce ideas off them, celebrate
    something, gripe about something, whatever. It seems to be easier
    for me to keep on task when other people are around.

Made a few minor tweaks to my research proposal. So far, so good.
 Getting closer.

Random Japanese sentence:
ÃƒÂ¥Ã‚Â¤Ã‚Â§ÃƒÂ£Ã‚Â?Ã‚Â¾ÃƒÂ£Ã‚Â?Ã‚Â‹ÃƒÂ£Ã‚Â?Ã‚Â«ÃƒÂ¨Ã‚Â¨Ã‚Â€ÃƒÂ£Ã‚Â?Ã‚Â£ÃƒÂ£Ã‚Â?Ã‚Â¦ÃƒÂ£Ã‚Â€Ã‚Â?ÃƒÂ§Ã‚ÂŠÃ‚Â¬ÃƒÂ£Ã‚Â?Ã‚Â¯ÃƒÂ§Ã‚ÂŒÃ‚Â«ÃƒÂ£Ã‚Â‚Ã‚ÂˆÃƒÂ£Ã‚Â‚Ã‚ÂŠÃƒÂ¥Ã‚Â¿Ã‚Â
ÃƒÂ¥Ã‚Â®Ã‚ÂŸÃƒÂ£Ã‚Â?Ã‚Â ÃƒÂ£Ã‚Â€Ã‚Â‚ Broadly speaking, dogs are more
faithful than cats.
