#+TITLE: Switching mindsets

October 12th, 2007 -
[[http://sachachua.com/blog/p/4400][http://sachachua.com/blog/p/4400]]

One of the interesting side-effects of writing this book on Emacs is
 that I get to stretch my brain by trying out different ways to plan my
 day.

My Planner configuration had accreted to just the right kind of
 support over the past five years, and I've been using it without
 needing to think about it much That's part of the reason why it works
 so well for me. It's just part of my workflow. It has molded my brain,
 and vice versa. ;)

I'd like to write a really good chapter that also shows the best of
 org, so I'm going to either have to \_think\_ org, or find someone
 (talkative! ;) ) who does.

Right now, I'm working on how to use Emacs to manage schedules. I'm
 running into interesting differences between Planner and Org, and
 these differences give me a better appreciation for both.

In Planner, I'm used to scheduling a slew of tasks at a time and
 moving things around a bit, ordering and grouping my tasks visually.
 In Org, I don't have the ability to manually edit the agenda view, but
 I do have the ability to pull tasks in from lots of different
 locations. This doesn't quite support my old way of planning, but
 opens up new ones.

Here's what I'm learning in order to do things the Org way:

-  Keep my scheduled day as clear as possible, putting down only fixed
   appointments and things I absolutely need to do that day.
-  Add other items as planned, but focus only on the next few actions.
-  Separate my tasks by context to make it easy to pull out the next few
   applicable actions.

Random Emacs symbol: cos -- Function: Return the cosine of ARG.
