#+TITLE: Weekly review

October 7th, 2007 -
[[http://sachachua.com/blog/p/4388][http://sachachua.com/blog/p/4388]]

The highlights of my week were the conversations I had. From hot
 chocolate at Farcoast with Driss (whom I'd last met at the Wikinomics
 event in February) to hot chocolate at Linux Caffe with Michael (whom
 I'd just gotten to know over blogs and e-mail) to tea with Ian and
 Gabriel, my week was just packed with interesting conversations. Add
 to that the e-mail conversations I've been having and the connections
 I've made... wow. Great week learning more about this connecting
 thing. =) More thoughts on that later.

My work permit arrived! I'll be starting on Oct 15. I also took an
 English language test to prove my proficiency for the skilled worker
 permanent residency application, and I renewed my social insurance
 number as well.

Reading and writing -- I've been catching up with a number of
 Enterprise 2.0 blogs. Because Google Reader allows you to view past
 blog entries by scrolling down, it was easy for me to read, say, all
 of [[http://www.elsua.net][Luis Suarez's posts on Elsua.net]]. I've
 also been working on my book. Less writing this week, more playing
 around with Emacs. I took another look at Org-mode and realized that
 it has a number of cool features that I'd wanted to do in Planner, so
 I might move more of my config over---maybe even make it more of the
 focus of my book, as it's built into recent versions of Emacs.

Speaking of code: I added many features to my interviewbot in Second
 Life. I sent the latest version to Stephen Perelgut. It includes a
 factory that creates an interviewbot based on a stored notecard and
 personalized for a particular avatar.

I tried out the static trapeze last Tuesday. Although the static
 trapeze was closer to the ground than the flying trapeze I tried a few
 months ago, I found it scarier because I didn't have a safety harness
 on and had to rely on the instructor spotting me. I didn't complete
 the two-hour lesson because my hands hurt so much that I couldn't hang
 on to the bars, but that's just because I haven't developed calluses.
 It's great exercise and upper-body conditioning, though, and I'm
 looking forward to going back next week. Thinking of the trapeze has
 also helped me build more exercise into my daily schedule. Today I did
 100 crunches, which will come in handy when I need to get my knees up
 and over the bar!

As for cooking: we made lemon chicken last Friday, and we made
 sinigang today. Yummy!

Random Emacs symbol: combine-after-change-execute -- Function: This
function is for use internally in `combine-after-change-calls'.
