#+TITLE: Writing plans for the chapter on managing notes

January 9th, 2008 -
[[http://sachachua.com/blog/p/4664][http://sachachua.com/blog/p/4664]]

- [ ] Keeping Notes in Emacs
 Structured vs Unstructured (outline, free-form)
 Flat vs Hyperlinked
 Private vs Public
 File structure (one file, daily, snippets)

In this section, you'll learn about the different kinds of notes you
take, and you will be able to choose one or two Emacs modules to start
learning.

- [ ] Capture and retrieve -- Remember, search

Getting the ideas out of your head and into your note-taking system;
searching your notes (basic), searching your notes (specific)

Wicked cool code: Remembering to different note-taking systems,
searching different note-taking systems

- [ ] Outline Notes with Org, Blorg

In this section, you'll learn how to keep outlined notes using Org.Â
You'll be able to create headings, sub-headings, and text notes. You'll
also learn how to manage outline items by promoting, demoting, and
rearranging them. These basic editing commands are covered in the Emacs
Org manual, so I'll just give a brief summary..

You'll also get tips on how to capture text quickly (M-x remember,
dabbrev), work with large outline files (split windows are useful), and
search your notes efficiently (searching headings or text).

Lastly, you'll learn how to publish your Org file as HTML or LaTeX.

Wicked cool code would be: searching, how to import to and export from
Freemind, a graphical mind-mapping program.

- [ ] Daily Notes with Planner

In this section, you'll learn how to write a day-based journal using
Planner. In addition to free-form notes on the page, you'll also be able
to keep semi-structured notes typed in manually or captured using
Remember. You'll also learn how to publish the resulting pages as HTML
and RSS, and how to customize the output.

Wicked cool code would be: searching notes and displaying matching
headlines, private notes, publishing note headlines, and publishing a
note index.

- [ ] Hyperlinked Notes with Muse

In this section, you'll learn how to create a personal wiki using Muse.Â
You'll learn how to create pages, link to pages, and publish your wiki.

Wicked cool code: Capturing notes to specific pages using Remember and
keyword matches, private pages, publishing pages when you save them.

- [ ] Snippets with Howm

In this section, you'll learn how to manage random snippets of
information using Howm.

- [ ] Blogging from Emacs -- WordPress, LJ, Blogger,Muse-Blosxom,
EmacsAtomAPI

In this section, you'll learn how to use Emacs as a blogging client for
many popular platforms. This is mainly for keeping other blogs in sync,
although I'll also talk about the possibility of using planner-rss +
something like Feedwordpress.

- [ ] Encrypted Notes (full file, segments) -- MOSTLY WRITTEN

In this section, you'll learn how to encrypt your notes. Actually, this
will probably be split up into the different tools...
