#+TITLE: From Eclipse to Emacs: Drupal development with Subversion, tags,
templates, and xdebug

July 29th, 2008 -
[[http://sachachua.com/blog/p/5007][http://sachachua.com/blog/p/5007]]

Yesterday, I started working on my Drupal project in Emacs. I can't
believe I hadn't moved to Emacs earlier. =)

I really like being able to diff a file with C-x v = (vc-diff) and check
in a file with C-x v v (vc-next-action). I also like the way that
svn-status (from psvn.el) lets me examine a directory tree, mark a set
of files, and commit them--all without using the mouse. I probably
should've set up keyboard shortcuts for these in Eclipse, but Eclipse
made it too easy to just use the mouse. Emacs encourages you to use the
keyboard, and it's easy to customize any keyboard shortcut.

php-mode's C-c . (php-show-arglist) works beautifully with the TAGS file
that I'd set up using Exuberant Ctags, so I don't need to do anything
special in order to get function definitions. Definition functions for
PHP functions would be nice. In the meantime, there's C-c C-f
(php-search-documentation).

The yasnippet template engine came in handy when I was writing test
cases. I updated
[[http://sachachua.com/notebook/elisp/snippets/php-mode/drupal-mode/dmodule][my
module template]] to include the simpletest hook, added a
[[http://sachachua.com/notebook/elisp/snippets/php-mode/drupal-mode/test][test
case template]], and added a template for the
[[http://sachachua.com/notebook/elisp/snippets/php-mode/drupal-mode/_simpletest][simpletest
hook]] as well. Yay dynamic templates!

And I just got Xdebug working with
[[http://www.emacswiki.org/cgi-bin/wiki/PhpMode][PhpMode and Geben]]...
Sweet!
