#+TITLE: After Emacs Conf 2013; ideas for Sunday and Monday

March 31st, 2013 -
[[http://sachachua.com/blog/p/24625][http://sachachua.com/blog/p/24625]]

Emacs Conf 2013 was a blast! It was super awesome meeting so many Emacs
geeks in person, and the talks were fascinating.
[[http://experivis.com/collection/emacsconf2013/][*I've posted my
sketchnotes*]]**and will be revising them to make them easier to read.
Some of the other speakers have shared their presentations, so I'll
update that page with links as I come across them. I'm working on
pulling together the videos (thanks to jamief for the livestream
recording, which I linked on the sketchnotes page). Our keynote wasn't
recorded on video, but I've uploaded the audio (also linked on the
sketchnotes page).

I'm flying out from London on Tuesday, April 2. The weather forecast for
Sunday and Monday looks great and this is the first time I've been in a
city with a (temporarily) high concentration of Emacs geeks. This is
also only the second time I've been in London, and the first with an
appreciable amount of free time. So I need to decide what to do,
otherwise I'll spend all the time working on Emacs-related follow-ups on
the couch.

*Possibilities/things to do:*

-  *Meet up with other Emacs geeks* at a coffee shop somewhere.
   Advantages of doing it in person instead of IRC: higher throughput,
   fewer tech problems, more ability to move things around or sketch
   things out? Although many Emacs geeks are still recovering from
   yesterday... Some possibilities:

   -  Braindump things to write about in more depth. (Outline for book?
      Pages on Emacs Wiki?) Emacs docathon!
   -  Hack on various things together. Maybe dig into Org issues? Emacs
      hackathon!
   -  Help people with their configuration files. Emacs configathon!
   -  Commiserate with other Windows users and borrow their
      configuration tweaks. Umm... Emacs unmiserathon?

-  *Hang out with other Emacs geeks*and do non-Emacsy things, like
   wandering around London, because people are awesome and it would be
   great to get to know them.
-  *Wander around London for walking exercise.*Have fish and chips. Have
   a good map to navigate my way back. Maybe walk up to Camden Town or
   take the tube? Go to the Museum of London and marvel at history?
-  *Wander around the neighbourhood.*Have a good map to navigate my way
   back.
-  *Write letters.*Because letters. =)
-  *Work on Emacs-related followups:*adding more information/colours to
   sketchnotes, processing video, writing blog posts, working on code...
   I can theoretically do this when I'm back in Toronto, but there's
   value in getting things out reasonably quickly and with good
   momentum.

Okay. I think the plan is to hang out and enjoy a nice relaxed day over
here, meeting up with John Wiegley or other Emacs people if they reach
out to the mailing list or through e-mail, and maybe wandering up to
Camden Town if not. I'll snag some postcards and write. Tomorrow, I'll
go to the Museum of London with my trusty notebook and pen, and collect
interesting thoughts. I'll block out some time every week to do Emacs
followup, so I can spread it out over time. Should be good!
