#+TITLE: Emacs chat intro

April 23rd, 2013 -
[[http://sachachua.com/blog/p/24684][http://sachachua.com/blog/p/24684]]

It turns out to be lots of fun to talk to other people about Emacs. You
pick up all sorts of tips and interesting ideas that way.

One of the reasons why I do these chats is to help people get a sense of
other people using Emacs. Now that I know John Wiegley sounds like when
he's excitedly talking about Emacs, it's so much more fun reading his
code. =) I'd love it if you told me a little bit about your story.
*Sharing how you got started with Emacs*(what helped, what needs work)
might give us ideas on how to make it easier for people to start. *What
was your “aha!” moment? What are the things you love, and what would you
like to see improved?*Walk me through your config, highlighting any
quirky things you've done to make Emacs fit the way you work.

*In addition to your story, you probably have lots of little tips that
could save people time or make their Emacs lives better.* No time to
blog or screencast? Show us your favourite tricks in a chat, and I'll
take care of putting it up on the Net. It's a quick way to get things
out of your brain and onto the Internet. =)

*If you have Emacs configuration or Lisp questions,*ask away. I might be
able to help, or someone listening might know the answer. We can spend
some time digging into code or bouncing around ideas. I'm happy to help
for free. If you come away with something incredibly useful, you can buy
me a virtual mug of hot chocolate through PayPal or make a donation
towards an awesome Emacs thing like EmacsWiki.org. =) It's all cool.

I'd love to record and share our conversation so that more people can
learn from it. If there are parts that you'd like blurred or not have
recorded, or if you prefer to not have the conversation recorded at all,
please tell me and I'll be happy to accommodate that.

Want to talk about Emacs? Get in touch with me at
[[mailto:sacha@sachachua.com][sacha@sachachua.com]]!
